Testintegration
ob-algdatii-ss18/leistungsnachweis-mamatofe pull request #25
Opened 2018-04-24 10:37 UTC by markuskr97

2018-04-24 14:23 UTC, skyfmmf requested changes
Ich habe da ein paar Anmerkungen. 

Grundsätzlich finde ich das so eine gute Art das zu integrieren. Diese Tests sollten bitt im Ordner lib/test stehen (und das Ding heißt sudoku ;) ).

2018-04-24 14:23 UTC, skyfmmf commented on CMakeLists.txt
> +    GIT_TAG master
Bitte lieber einen Tag von einem Release nehmen

2018-04-24 14:23 UTC, skyfmmf commented on CMakeLists.txt
> +include(CTest)
Hat das einen Grund, dass das jetzt drunter steht? Sonst bitte oben drüber lassen.

2018-04-24 14:23 UTC, skyfmmf commented on app/test/CMakeLists.txt
> -add_test(NAME sudoku-solverTest COMMAND sudoku-solver)
Der Test hier war schon als echter Test gedacht, bitte nicht einfach löschen

2018-04-24 14:23 UTC, skyfmmf commented on app/test/CMakeLists.txt
> +include_directories(${source_dir}/googletest/include
Bitte `target_include_directories` statt `include_directories` benutzen, siehe: [https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1](https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1)

2018-04-24 14:23 UTC, skyfmmf commented on app/test/CMakeLists.txt
> +        ${source_dir}/googlemock/include)
Brauchen wir googlemock?

2018-04-24 16:22 UTC, markuskr97 commented
Wenn ich das git-Tag auf ein Release ändere funktioniert der build nicht mehr ...

2018-04-24 16:27 UTC, markuskr97 commented on app/test/CMakeLists.txt
> +include_directories(${source_dir}/googletest/include
okay habe ich übernommen

2018-04-24 16:34 UTC, skyfmmf commented
Also ich kann da einfach

```cmake
    GIT_TAG release-1.8.0
```

schreiben und der Build geht noch. Was ist denn der Fehler bei dir?

2018-04-24 16:37 UTC, markuskr97 commented on app/test/CMakeLists.txt
> +        ${source_dir}/googlemock/include)
Ne funktioniert auch ohne ...

2018-04-24 16:37 UTC, skyfmmf requested changes

2018-04-24 16:37 UTC, skyfmmf commented on app/test/CMakeLists.txt
> -add_test(NAME sudoku-solverTest COMMAND sudoku-solver)
Bitte nicht löschen

2018-04-24 16:37 UTC, skyfmmf commented on app/CMakeLists.txt
> -add_subdirectory(test)
Bitte nicht löschen

2018-04-24 16:37 UTC, skyfmmf commented on lib/test/CMakeLists.txt
> +add_executable(sudoku_test sodukotest.cpp)
Da ist noch ein Typo im Dateinamen

2018-04-24 16:40 UTC, markuskr97 commented on lib/test/CMakeLists.txt
> +add_executable(sudoku_test sodukotest.cpp)
Habe ich geändert

2018-04-24 16:41 UTC, skyfmmf commented on app/test/CMakeLists.txt
> +        ${source_dir}/googlemock/include)
Sehr gut, dann bauen wir das erstmal nicht ein

2018-04-24 16:41 UTC, skyfmmf commented on app/test/CMakeLists.txt
> +include_directories(${source_dir}/googletest/include
Schau mal in app/CMakeLists.txt, da hab ich das schon mal gemacht, das geht schon.

2018-04-24 16:43 UTC, markuskr97 commented on app/test/CMakeLists.txt
> +include_directories(${source_dir}/googletest/include
Es gibt Compiler-Fehler, error: ....

2018-04-24 16:45 UTC, markuskr97 commented on app/CMakeLists.txt
> -add_subdirectory(test)
okay

2018-04-24 16:45 UTC, skyfmmf commented on app/test/CMakeLists.txt
> +include_directories(${source_dir}/googletest/include
Welchen Fehler denn genau?

2018-04-24 16:45 UTC, markuskr97 commented on app/test/CMakeLists.txt
> -add_test(NAME sudoku-solverTest COMMAND sudoku-solver)
okay

2018-04-24 17:02 UTC, skyfmmf commented
Das schaut so weit ganz gut so weit. 

Unter [https://coveralls.io/builds/16674163](https://coveralls.io/builds/16674163) kann man sehen, dass wir noch die Coverage für die googletest-Dateien mitmessen. Wenn du in der travis.yml bei dem Aufruf von coveralls noch ein `--exclude build/gtest/` einfügst, ist das auch noch gelöst.

2018-04-25 09:56 UTC, skyfmmf approved these changes

2018-04-25 09:57 UTC, merged